# WINDOW RULES

windowrule=float,^(pavucontrol)$ # Pavucontrol
windowrule=float,title:^(Library)$ # Firefox downloads window
windowrule=float,title:^(Eclipse)$ # eclipse

windowrule=float,^(org.freedesktop.impl.portal.desktop.kde)$ # kde portal
